apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatapp

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets-template.yaml
  - mysql/pvc.yaml
  - mysql/service.yaml
  - mysql/deployment.yaml
  - backend/service.yaml
  - backend/deployment.yaml
  - frontend/service.yaml
  - frontend/deployment.yaml
  - nginx/service.yaml
  - nginx/deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/name: chatapp
      app.kubernetes.io/part-of: chatapp

commonAnnotations:
  app.kubernetes.io/version: "1.0.0"

images:
  - name: chatapp-backend
    newTag: "latest"
  - name: chatapp-frontend
    newTag: "latest"
  - name: chatapp-mysql
    newTag: "latest"
  - name: chatapp-nginx
    newTag: "latest"

replicas:
  - name: backend
    count: 2
  - name: frontend
    count: 2
